application: web-duels
runtime: python27
threadsafe: no
api_version: 1

version: 1

handlers:
  - url: /js/*
    static_dir: static/js
    
  - url: /bower_components/*
    static_dir: static/bower_components

  - url: /css/*
    static_dir: static/css

  - url: /images/*
    static_dir: static/img

  - url: /partials/*
    static_dir: static/partials

  - url: /.*
    static_files: static/html/index.html
    upload: static/html/index.html
