application: web-duels
version: poc
runtime: python27
threadsafe: true
api_version: 1

handlers:
  - url: /js/*
    static_dir: static/js

  - url: /css/*
    static_dir: static/css

  - url: /images/*
    static_dir: static/img

  - url: /partials/*
    static_dir: static/partials

  - url: /_ah/spi/.*
    script: services.services
    secure: always

  - url: /callback
    script: frontend.application

  - url: /backend/.*
    script: backend.application
    secure: always
    login: admin

  - url: /.*
    script: frontend.application
    secure: always

libraries:
  - name: webapp2
    version: latest

  - name: jinja2
    version: latest

  - name: endpoints
    version: latest

  - name: pycrypto
    version: latest
